apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pizza-api
  namespace: default
  labels:
    app: pizza-api
    version: v1
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: pizza-api:latest
      importPolicy:
        scheduled: false
